# Implementação do Algoritmo génetico

 a + 2b + 3c + 4d = 30

In [1]:
import numpy as np

## Criação da matriz dos cromossomos (6,4) selecionado aléatoriamente

In [2]:
num_crom = 6  #numero de Cromossomos
num_gen = 4   #numero de genes
num_Total_gene = num_crom*num_gen
Taixa_De_Cruzamento = 0.25
Taixa_De_Mutação = 0.1

In [3]:
# np.random.seed(30)
cromossomos = np.random.randint(0,30,(num_crom,num_gen))
cromossomos

array([[29, 27, 20, 19],
       [27, 28,  0, 28],
       [ 9, 22, 20, 18],
       [ 9,  8, 24,  7],
       [11, 18, 15, 10],
       [20, 23, 26, 17]])

Assim Definimos como **" f() = ( a + 2b + 3c + 4d ) - 30 "**  a função objetiva

## Inicialização dos coeficientes da função objetiva

In [4]:
coeficiente =[1,2,3,4]
coeficiente

[1, 2, 3, 4]

## Calculo da Avaliação Objetiva

In [5]:
F = cromossomos * coeficiente 
Av_Ob = abs(F.sum(1)-30)
Av_Ob

array([189, 165, 155,  95, 102, 182])

 ## Adaptação da função objetiva

In [6]:
Ad_Ob = 1 / ( 1 + Av_Ob )
Ad_Ob

array([0.00526316, 0.0060241 , 0.00641026, 0.01041667, 0.00970874,
       0.00546448])

## Probabilidade da função Objetiva

In [7]:
Pro_Ob = Ad_Ob / Ad_Ob.sum()
Pro_Ob

array([0.12158638, 0.13916514, 0.14808598, 0.24063972, 0.22428556,
       0.12623723])

## Probabilidade Accumulativa

In [8]:
Pro_Acc = Pro_Ob.cumsum()
Pro_Acc

array([0.12158638, 0.26075152, 0.4088375 , 0.64947721, 0.87376277,
       1.        ])

# Gerar Novo Cromossomos

 ### Seja r um array de uma dimenção de numeros aleatórios entre (0,1)

In [9]:
r = np.random.rand(num_crom)
r

array([0.50388328, 0.85308098, 0.1856329 , 0.28542171, 0.77785484,
       0.44051595])

Estamos achando aqui o indice Teto em que percence a lista aleatoria **R** nos intervales da Pro_Acc. 

In [10]:
indice = np.searchsorted(Pro_Acc,r, side='left')
indice

array([3, 4, 1, 2, 4, 3])

Criação de novos cromossomos usando o indice anterior.

In [11]:
novo_cromossomos = np.zeros_like(cromossomos)
novo_cromossomos = cromossomos[indice]
novo_cromossomos

array([[ 9,  8, 24,  7],
       [11, 18, 15, 10],
       [27, 28,  0, 28],
       [ 9, 22, 20, 18],
       [11, 18, 15, 10],
       [ 9,  8, 24,  7]])

Subtituindo a antiga matriz de cromossomos com os novo_cromossomos gerados. 

In [12]:
cromossomos = np.copy(novo_cromossomos)
cromossomos

array([[ 9,  8, 24,  7],
       [11, 18, 15, 10],
       [27, 28,  0, 28],
       [ 9, 22, 20, 18],
       [11, 18, 15, 10],
       [ 9,  8, 24,  7]])

# Cruzamento

### Gerar novas valores aleatorios

In [13]:
r0 = np.random.random(num_crom)
r0

array([0.61884617, 0.24380332, 0.0432954 , 0.52235541, 0.85872113,
       0.68467003])

 ### Com a Taixa de Cruzamento nos iremos achar os indices dos valores r0 inferior. 

In [14]:
indice_cruzamento = np.argwhere(r0 < 0.25)
indice_cruzamento = indice_cruzamento.ravel().tolist()
indice_cruzamento

[1, 2]

 ### Gerarmos valores aleatorios para determinar o Ponto de Corte dos cromossomos

In [15]:
Pt_corte = np.random.randint(1,num_gen-1,size=len(indice_cruzamento))
Pt_corte = Pt_corte.tolist()
Pt_corte

[2, 1]

In [16]:
Tam_ind_Cruz = len(indice_cruzamento) #O tamanho do indice de Cruzamento
Tam_ind_Cruz

2

### Esta matriz foi criada para agrupar o conjunto de cromossomos que soferão o cruzamento

In [17]:
matriz_cross = (cromossomos[indice_cruzamento]).reshape(Tam_ind_Cruz,num_gen)
matriz_cross

array([[11, 18, 15, 10],
       [27, 28,  0, 28]])

### Criação de uma Matriz 0 tendo a mesma caractéristica que a matriz de crusamento para receber os valores dos genes dos cromossomos cruzados

In [18]:
novo_cs = np.zeros_like(matriz_cross)
novo_cs

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

### O cruzamento é effectuado aqui seguindo a ordem das linhas da matriz_cross. vale ressaltar que a ultima linhas tem que cruzar com a primeira.

In [19]:
tam = len(matriz_cross)
for j in range(tam):
    if j!= (tam-1):
        novo_cs[j] = np.concatenate( ( matriz_cross[j][:Pt_corte[j]], matriz_cross[j+1][Pt_corte[j]:]))
    elif j == (tam-1):
        novo_cs[j] = np.concatenate( ( matriz_cross[j][:Pt_corte[j]], matriz_cross[0][Pt_corte[j]:]))
novo_cs


array([[11, 18,  0, 28],
       [27, 18, 15, 10]])

### Substituição dos cromossomos cruzados dentro da matriz Cromossomos

In [20]:
tam = len(indice_cruzamento)
for j in range (tam):
    cromossomos[indice_cruzamento[j]] = novo_cs[j]
cromossomos

array([[ 9,  8, 24,  7],
       [11, 18,  0, 28],
       [27, 18, 15, 10],
       [ 9, 22, 20, 18],
       [11, 18, 15, 10],
       [ 9,  8, 24,  7]])

## Mutação

 ### Calculo dos numeros de mutante e seu arredondamento

In [21]:
num_Mutante = (num_Total_gene * Taixa_De_Mutação)
num_Mutante = round(num_Mutante)

### Gerando as POSIÇÔES dos mutantes acima do numero Total de genes

In [22]:
Pos_mutante = np.random.randint(1,num_Total_gene,num_Mutante)
Pos_mutante

array([ 7, 15])

### Gerando os VALORES  das posições mutantes.

In [23]:
Val_Mutante = np.random.randint(1,num_Total_gene,num_Mutante)
Val_Mutante

array([2, 7])

### Representando em linha os genes dos cromossomos

In [24]:
n= cromossomos.reshape(1,24)
n

array([[ 9,  8, 24,  7, 11, 18,  0, 28, 27, 18, 15, 10,  9, 22, 20, 18,
        11, 18, 15, 10,  9,  8, 24,  7]])

### Subtituindo os valores mutantes respectivamente nas posições mutantes, dentro dos vetores de genes de cromossomos

In [25]:
n = np.copy(cromossomos.reshape(1,24)).ravel()
n[Pos_mutante] = Val_Mutante
n

array([ 9,  8, 24,  7, 11, 18,  0,  2, 27, 18, 15, 10,  9, 22, 20,  7, 11,
       18, 15, 10,  9,  8, 24,  7])

### Reorganizando o vector de gene mutado em matriz de cromossomos

In [26]:
cromossomos = np.copy(n.reshape(num_crom,num_gen))
cromossomos

array([[ 9,  8, 24,  7],
       [11, 18,  0,  2],
       [27, 18, 15, 10],
       [ 9, 22, 20,  7],
       [11, 18, 15, 10],
       [ 9,  8, 24,  7]])